### ISSUE TITLE
Complement the _Dynamic.html feature with a Dynamic PageCode

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/WebEngine#163]
At the moment, unknown urls are passed to the _Dynamic.html PageView but must be processed by a _Common PageCode.  The common pagecode must then check to see if an actual page has been requested rather than a dynamic one, before performing its dynamic processing.

It would be good if PHP.Gt treated _Common as normal (for all requests) but then called a _Dynamic pagecode if (and only if) this was a dynamic request.

If no _Dynamic PageCode or PageView exist, a 404 should still be thrown.

**Comment by g105b** [comment]
Can confirm this will be made as a feature soon.

**Comment by g105b** [comment]
Please see https://github.com/PhpGt/WebEngine/wiki/Dynamic-URIs-and-Pages for implementation documentation.
