### ISSUE TITLE
Head file compilation may not work in production mode

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/WebEngine#230]
manifest md5ing is skipped if isProduction is set, so long as the .cache file exists.  This is fine for applications with a single head, but doesn't that result in different head fingerprints remaining uncompiled?

**Comment by g105b** [comment]
`static-fingerprint` file needs to be renamed to `static-fingerprint-{HASH}` where HASH is an md5 of the file **names** only (not the contents).

The FileOrganiser will then know whether the _current_ head is compiled already or not.

**Comment by g105b** [comment]
This will be changed completely in v3 build system.
