### ISSUE TITLE
Readme needs updating

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/WebEngine#252]
It refers to tools like CSRF being part of the webengine, which they aren't.  The link to CSRF should probably go to the csrf module too, rather than a webengine wiki page - otherwise the info is being maintained in two different places.

**Comment by g105b** [comment]
I plan on creating an overview page for CSRF in the webengine wiki to explain how CSRF is automatically included in webengine projects. That page can link to the CSRF wiki.
