### ISSUE TITLE
Head file compilation: CRC32 rather than MD5?

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/WebEngine#256]
Looking at some Benchmarks,  CRC32 hashes appear to be significantly (up to 50%) quicker than MD5 - but they generate a hash that is a quarter the length of an MD5 so collisions are more likely.  

As the headfile manifesting process requires a hash of all script and style files to be generated for every page request, is it worth moving to CRC32 instead of MD5?

**Comment by g105b** [comment]
This will be answered by the v3 build system.
