### ISSUE TITLE
ID's in URL Path

### ISSUE THREAD

**Issue by christopher-paul-shaw** [PhpGt/WebEngine#257]
Looking into using Sub Directories as ID's using mod_rewrite. Uncertain if the webengine is causing this behaviour or poor rewrite rules.

Scenario
URL: examplesite.com/blog/SLUGOFTHEARTICLE/
to pass to an existing file in src/page
Target: /www/blog.php?id=SLUGOFTHEARTICLE

```
  RewriteRule ^blog\/(.*)$ blog.php?id=$1 [QSA,L]

```

In different cases it acts differently. If I create a file called test.php  in www and point the RewriteRule there, then /blog/myslug runs test.php and echos out myslug

If I change it to the blog.php which I want to actually handle the id, I am given an Errorr 404 by the WebEngine.

**Comment by g105b** [comment]
No need for rewrite rules.

If you want to have examplesite.com/blog/slug123 and examplesite.com/blog/slug456 handled by the same logic file and sharing the same page template, do this:

+ `src/page/blog/_common.php` - put your code here that executes all pages under blog/*
+ `src/page/blog/_dynamic.html` - put the template file here that will be used for all pages under blog/*

An example would be to use the _common.php to load the corresponding markdown file from the URL, then replace an element in the _dynamic.html for where the content should be placed.

Let me know if that makes sense or if you would like me to provide a more in depth example?
