### ISSUE TITLE
Simplify nginx config block?

### ISSUE THREAD

**Issue by clarkcx** [PhpGt/WebEngine#319]
Rather than pointing to `/var/www/example/vendor/phpgt/webengine/go.php` in the nginx config, how about pointing to `/var/www/example/go.php` for reasons of simplicity?

**Comment by g105b** [comment]
This is good. Not blocking v3 stable release, but it can come after release as a nice little bonus.

**Comment by g105b** [comment]
Look at using a post-install Composer script to link the file here: https://getcomposer.org/doc/articles/scripts.md

**Comment by g105b** [comment]
Sorted in documentation.
